import { Metadata } from "next";
import { LandingPageTemplate } from "@/components/LandingPageTemplate";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const slug = "/disclaimer";

export const metadata: Metadata = {
  title: "Disclaimer — QR Forge",
  description: "Read the QR Forge legal disclaimer regarding the use of our generator tools and services.",
  alternates: { canonical: slug },
};

export default function DisclaimerPage() {
  return (
    <>
      <Header />
      <main className="main">
        <LandingPageTemplate
          slug={slug}
          title="Disclaimer"
          subtitle="Legal notices and limitations of liability."
          content={
            <div className="editorial-content">
              <p><em>Last Updated: May 2026</em></p>
              
              <h2>1. General Information</h2>
              <p>The information and tools provided by QR Forge (the "Site") are for general informational and utility purposes only. All information and tools on the Site are provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or generated content on the Site.</p>
              
              <h2>2. No Professional Advice</h2>
              <p>The Site cannot and does not contain legal, financial, or professional advice. The use or reliance of any information contained on the site or generated by our tools is solely at your own risk.</p>
              
              <h2>3. Tool Usage & Reliability</h2>
              <p>While we strive to produce standards-compliant QR codes, we do not guarantee that the generated QR codes will be scannable by all devices or apps in all conditions. Users are strongly advised to thoroughly test any generated QR code with multiple devices before printing or distributing them commercially.</p>
              
              <h2>4. External Links</h2>
              <p>The Site may contain links to external websites that are not provided or maintained by or in any way affiliated with QR Forge. Please note that we do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.</p>
              
              <h2>5. Errors and Omissions</h2>
              <p>We assume no responsibility or liability for any errors or omissions in the content of this site or the output of our tools. The information contained in this site is provided on an "as is" basis with no guarantees of completeness, accuracy, usefulness, or timeliness.</p>
            </div>
          }
        />
      </main>
      <Footer />
    </>
  );
}
